# Replace the absolute path, username and group before using this example.
/home/mark/external-ip-monitor/var/history.jsonl {
    daily
    rotate 30
    compress
    delaycompress
    missingok
    notifempty
    su mark mark
    create 0600 mark mark
}
